[package]
name = "cue"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
clearscreen = "4.0.3"
colored = "3.1.1"
dunce = "1.0.5"
notify = "8.2.0"
terminal_size = "0.4.3"
which = "8.0.0"

